### PR TITLE
Added .exe to output files in windows ,fix-111, fix-108, fix-103

### PR DESCRIPTION
**Pull request by Salil03**
All output files shouldve have ".exe" added after them in windows

### CODE REVIEW

**Comment by Salil03** [comment]
For some reason github actions is failing build

**Comment by Salil03** [comment]
Even though build is failing here, I think it can be merged because it builds locally. I suspect this is an issue in github actions

**Comment by Salil03** [comment]
@mfornet you are free to review this. I am done

**Comment by mfornet** [comment]
Excellent, I'll review over the week

**Comment by Salil03** [comment]
Bump

**Review by mfornet — APPROVED** [review]

**Pull request merged**
