### PR TITLE
Resolve #139: added an autoOpen option

### LINKED ISSUE #139: How to prevent acmx from opening a new VSCode instance?
Generally, I am running a workspace to solve tasks. 

When I click the button to parse a new task, the workspace is closed automatically and a new folder is opened instead. Then I need to reopen my configured workspace to get my developing environment set.

I wonder, if there is an option to prevent such behavior? Thanks in advance.

### PR DESCRIPTION
**Pull request by ftiasch**

### CODE REVIEW

**Comment by ftiasch** [comment]
It seems that `package.json` configures a run test path prefix with `out/` while `tsconfig.json` says that the `outDir` should be `dist/...`. 

I fixed the test command and now the tests run smoothly on my machine.

**Comment by mfornet** [comment]
@ftiasch the PR works; but I wonder if it solves your particular problem. I was expecting you to download the problem to the current working directory; otherwise it will be downloaded to the usual place and you will have no feedback of it being downloaded at all; and you will need to manually open the specific folder where it was downloaded.

Is this the expected behaviour?

**Comment by mfornet** [comment]
Fixes #139

**Comment by ftiasch** [comment]
> @ftiasch the PR works; but I wonder if it solves your particular problem. I was expecting you to download the problem to the current working directory; otherwise it will be downloaded to the usual place and you will have no feedback of it being downloaded at all; and you will need to manually open the specific folder where it was downloaded.
> 
> Is this the expected behaviour?

Yes! Usually, I have a VSCode workspace running  which contains some workspace-specified settings & extensions. In particular, the `acmx` extension is enabled in this workspace. Let's say my workspace already opened the folder `SOLVING_PATH`.Then, I use the CompetitiveCompanion to download tasks and tests to the folder `SOLVING_PATH`. 

Without this PR, the `SOLVING_PATH`  folder is automatically opened, replacing my nicely configured workspace, which is undesired for me. Thus, I simply add an option to disable such behavior.

**Review by mfornet — APPROVED** [review]

**Pull request merged**
