### PR TITLE
Added oj instead of cf-submit

### PR DESCRIPTION
**Pull request by Salil03**
Adds oj command to submit: https://github.com/online-judge-tools/oj

Install it using `pip3 install online-judge-tools`

First login using `oj login URL`. Example: `oj login https://codeforces.com/`

Supported judges for submission are 

- AtCoder
- Codeforces
- Topcoder (Marathon Match)
- yukicoder
- HackerRank
- Toph (Problem Archive)

### CODE REVIEW

**Comment by mfornet** [comment]
This tool you are suggesting looks awesome! I'm wondering if we should make this as the default tool and in addition create a configuration that allows user to setup its preferred submit way. Just thinking in those already committed to `cf-submit`.

**Comment by mfornet** [comment]
Also this will require adding/modifying relevant entries to the wiki.

**Comment by Salil03** [comment]
> This tool you are suggesting looks awesome! I'm wondering if we should make this as the default tool and in addition create a configuration that allows user to setup its preferred submit way. Just thinking in those already committed to `cf-submit`.

Is there any benefit of `cf-submit` over oj aside from the fact that we are using it right now?

**Comment by mfornet** [comment]
> Is there any benefit of `cf-submit` over oj aside from the fact that we are using it right now?

Tbh, I haven't used neither. The only immediate drawback I see, is for users who are currently using `cf-submit` that we are going to break their pipelines :(

**Comment by mfornet** [comment]
I won't merge this, instead I will use a separate setting to provide which command line to use on submit. The command line can use `$URL` and `$CODE`

**Pull request closed without merging**
